CREATE DATABASE BD4;
USE BD4;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    EMP_NAME VARCHAR(25),
    EMP_DOB DATE,
    EMP_AGE INT
);

CREATE TABLE PRODUCT(
	PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(50),
    PRICE DOUBLE,
    MANUFACTURING_DATE DATE
);

CREATE TABLE STUDENT(
	STUDENT_ID smallint,
    STUDENT_NAME VARCHAR(50),
    AGE TINYINT,
    HEIGHT FLOAT
);

CREATE TABLE ARTICLE(
	ARTICLE_ID INT,
    TITLE TEXT(200),
    CONTENT TEXT
);

CREATE TABLE EMPLOYEES1(
	EMP_ID INT,
    EMP_NAME VARCHAR(50),
    GENDER ENUM("MALE","FEMALE","OTHER"),
    JOB_ROLE ENUM("DEVELOPER","MANAGER","TESTER")
);

CREATE TABLE STUDENT1(
	STUDENT_ID INT,
    STUDENT_NAME VARCHAR(50),
    HOBBIES SET("READING","MUSIC","SPORTS","TRAVELLING")
);

CREATE TABLE COLOR(
	PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(50),
    COLOR ENUM("RED","BLUE","GREEN","WHITE")
);

CREATE TABLE MEMBERSHIP_LEVEL(
	MEMBER_ID INT,
    MEMBER_NAME VARCHAR(50),
    MEMBER_TYPE ENUM("BASIC","SILVER","PLATINUM")
);